# Generated by Django 4.2.1 on 2023-06-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_products_user',
            name='id_product_discont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.product_discount'),
        ),
    ]
