# Generated by Django 4.2.1 on 2023-06-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_products_user_id_product_discont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_products_user',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.product_admin'),
        ),
    ]
