# Generated by Django 4.2.1 on 2023-06-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_products_user_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_admin',
            name='data_time',
            field=models.DateField(null=True),
        ),
    ]
