# Generated by Django 4.2.1 on 2023-06-12 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_order_admin_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_companu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.user_comp_shop')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
